-- ============================================
-- RLS POLICIES - DEPRECATED
-- ============================================
-- 
-- ⚠️ THIS FILE IS DEPRECATED
-- 
-- Please use: secure_rls_policies.sql
-- 
-- The helper functions in this file (is_admin, is_teacher, etc.)
-- caused circular dependency issues when querying the profiles table.
-- 
-- The new secure_rls_policies.sql file:
-- ✅ Has no circular dependencies
-- ✅ Prevents role escalation
-- ✅ Prevents grade manipulation
-- ✅ Enforces active user checks
-- 
-- ============================================

-- To apply the secure policies, run:
-- secure_rls_policies.sql

-- DO NOT USE THIS FILE
